### ISSUE TITLE
Cannot find tailwind on linux amd64

### ISSUE THREAD

**Issue by vKito** [MJRasicci/Tailwind.MSBuild#14]
Hello. This looks cool. I'm having an issue on Pop!_OS which identifies as `amd64` so it becomes `tailwindcss-linux-amd64` in the call to `ProcessorArchitecture.CurrentProcessArchitecture.ToLower()`, however the tailwind github release only specifiy a `tailwind-linux-x64`.

Is there some override that I can configure? Thanks

**Comment by vKito** [comment]
Thank you for the quick reply. It's now complaining about permission denied on the solution path.

My colleague on a Mac OSX ventura 13.0.1 has the same problem

```
  Tailwind.MSBuild.targets(9, 5): [MSB4018] The "BuildTailwindCSS" task failed unexpectedly.
System.ComponentModel.Win32Exception (13): An error occurred trying to start process '~/.nuget/packages/tailwind.msbuild/1.0.1/cli/latest/tailwindcss-linux-x64' with working directory '~/dev/work/web-stack-poc/src/Web/Properties/'. Permission denied
```

**Comment by MJRasicci** [comment]
I believe this is caused by the filesystem permissions on the newly downloaded binary. If you could try running `chmod +x '~/.nuget/packages/tailwind.msbuild/1.0.1/cli/latest/tailwindcss-linux-x64'` and then building your project again to confirm that would be helpful. The binary will not be redownloaded unless your nuget package cache is cleared or a new tailwind version is released so you won't need to do this before every clean build.

Assuming that resolves the issue, I will need to look into a way of setting the file permissions programmatically so other users don't run into the same issue and to prevent the error in CI/CD builds.

Thanks again

**Comment by MJRasicci** [comment]
> The binary will not be redownloaded unless your nuget package cache is cleared or a new tailwind version is released so you won't need to do this before every clean build.

I lied. Apparently, I forgot to delete a couple lines I added for debugging purposes so it was being redownloaded every time.

> I will need to look into a way of setting the file permissions programmatically so other users don't run into the same issue and to prevent the error in CI/CD builds.

#17 created to track effort on this.

**Comment by MJRasicci** [comment]
@vKito With the release of v1.0.2 the previously mentioned caching issue and POSIX file permissions have been resolved. Thanks for reporting your issues!

**Comment by vKito** [comment]
I got it working with version 1.0.2. 
Thank you so much for taking the time to look into this
